"""
core/phi_magnet.py
Hidden Engine: Potential Function & Euclidean Vector Attraction.

Models price as a particle in a gravitational field generated by institutional liquidity nodes.
Computes attraction vectors and scalar potential energy at each timestep.

Mathematical Foundation:
$$
\Phi_{\text{mag}}(\mathbf{x}) = -\sum_{j=1}^{N} \frac{G \cdot L_j}{\|\mathbf{x} - \mathbf{z}_j\|^\alpha + \epsilon}
$$
$$
\vec{F}_{\text{pull}} = -\nabla \Phi_{\text{mag}}
$$
"""

import numpy as np
from typing import Tuple, Optional

class PhiMagnet:
    def __init__(self, gravity: float = 0.72, exponent: float = 1.8, epsilon: float = 1e-6):
        self.G = gravity
        self.alpha = exponent
        self.eps = epsilon

    def compute_potential(self, prices: np.ndarray, liquidity_nodes: np.ndarray) -> np.ndarray:
        """Scalar potential field $\Phi_{\text{mag}}$ at each price point."""
        prices = np.asarray(prices, dtype=np.float64)
        nodes = np.asarray(liquidity_nodes, dtype=np.float64).flatten()
        
        # Broadcasting: (N, 1) - (1, M) -> (N, M)
        dists = np.abs(prices[:, None] - nodes[None, :])
        dists = np.maximum(dists, self.eps)
        
        potential = -np.sum(self.G / (dists ** self.alpha), axis=1)
        return potential

    def compute_attraction_vectors(self, prices: np.ndarray, liquidity_nodes: np.ndarray) -> np.ndarray:
        """Returns directional pull vectors (+1 up, -1 down) weighted by proximity."""
        dists = np.abs(prices[:, None] - liquidity_nodes[None, :])
        directions = np.sign(liquidity_nodes[None, :] - prices[:, None])
        weights = 1.0 / (dists ** self.alpha + self.eps)
        
        # Net vector = weighted sum of directions
        net_pull = np.sum(directions * weights, axis=1) / (np.sum(weights, axis=1) + 1e-9)
        return net_pull

    def get_magnet_state(self, prices: np.ndarray, nodes: np.ndarray) -> dict:
        phi = self.compute_potential(prices, nodes)
        vec = self.compute_attraction_vectors(prices, nodes)
        return {"potential": phi, "attraction_vector": vec, "pull_magnitude": np.abs(vec)}
